<?php
$itemOption = $this->getData('item');
$buyRequest = $itemOption->getBuyRequest()->getData();
$order = $itemOption->getOrder();
$orderId = $order->getId();
?>
<?php //PDP order information ?>
<?php
$pdpConfig = Mage::getStoreConfig('integration');
if(isset($pdpConfig['setting']['enable']) && $pdpConfig['setting']['enable'] == 1) : ?>
	<?php 
	$pdpData = isset($buyRequest['pdp_option']) ? $buyRequest['pdp_option'] : array();
	$designId = isset($pdpData['design_id']) ? $pdpData['design_id'] : 0;
	$pdpProductId = isset($pdpData['pdp_product_id']) ? $pdpData['pdp_product_id'] : 0;
	$pdpUrl = Mage::helper('integration')->getPdpLink();
	?>
	<?php if($designId > 0) : ?>
		<div class="pdp-design-infor">
			<?php $dataDesign = Mage::helper('integration')->getPdpDesignOrder($designId); ?>
			<?php $strImages = $dataDesign['side_thumb']; ?>
			
			<?php if($strImages != '') : ?>
				<?php $images = unserialize($strImages); ?>
				<?php if(count($images)) : ?>
					<?php echo $this->__('Preview Design: ') ?>
					<?php foreach($images as $image) : ?>
						
						<?php if($image['thumb'] == '') { continue; } ?>
						<?php 
						$sideId = isset($image['sideId']) ? $image['sideId'] : 0;
						$sideData = Mage::helper('integration')->getPdpSideData($sideId);
						$sideTitle = $sideData['side_name'] ? $sideData['side_name'] : '';
						?>
						<a href="<?php echo $pdpUrl.$image['thumb']; ?>">[<?php echo $sideTitle; ?>]</a>  
					<?php endforeach; ?>
				<?php endif; ?>
			<?php endif; ?>
		</div>
		<a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK) ?>sales/order/view/order_id/<?php echo $orderId ?>/"><?php echo $this->__('View Detail in Store') ?></a>
	<?php endif; ?>
<?php endif; ?>



