<?php
$itemOption = $this->getData('item');
$buyRequest = $itemOption->getBuyRequest()->getData();
?>
<?php //PDP order information ?>
<?php
$mDesignId = $this->getRequest()->getParam('design_id',0);
$pdpConfig = Mage::getStoreConfig('integration');
if(isset($pdpConfig['setting']['enable']) && $pdpConfig['setting']['enable'] == 1) : ?>
	<?php 
	$pdpData = isset($buyRequest['pdp_option']) ? $buyRequest['pdp_option'] : array();
	$designId = isset($pdpData['design_id']) ? $pdpData['design_id'] : 0;
	$pdpProductId = isset($pdpData['pdp_product_id']) ? $pdpData['pdp_product_id'] : 0;
	$pdpUrl = Mage::helper('integration')->getPdpLink();
	?>
	<?php if($designId > 0) : ?>
		<div class="pdp-design-infor">
			<?php $dataDesign = Mage::helper('integration')->getPdpDesignOrder($designId); ?>
			<?php $strImages = $dataDesign['side_thumb']; ?>
			<?php if($strImages != '') : ?>
				<?php $images = unserialize($strImages); ?>
				<?php if(count($images)) : ?>
					<?php foreach($images as $image) : ?>
						<?php if($image['thumb'] == '') { continue; } ?>
						<img src="<?php echo $pdpUrl.$image['thumb'] ?>" />
					<?php endforeach; ?>
				<?php endif; ?>
			<?php endif; ?>
		</div>
		<span class="pdp-design-infor-item"><a id="pdp-design-infor-item-zip-<?php echo $designId; ?>" href="#"><?php echo $this->__('Zip Design') ?></a></span>
	<?php endif; ?>
	<input type="hidden" id="pdp-desgin-id-<?php echo $designId; ?>" value="<?php echo (int)$mDesignId ?>" />
	<script type="text/javascript">
	jQuery(document).ready(function($){
		var designId = '<?php echo $designId; ?>';
		var intDesingId = $('#pdp-desgin-id-'+designId).val();
		if(designId == intDesingId)
		{
			intDesingId = parseInt(intDesingId);
			if(intDesingId > 0)
			{
				//downloadPdpDesign(intDesingId);
			}
		}
		$('#pdp-design-infor-item-zip-'+designId).click(function(e){
			downloadPdpDesign(designId);
		})
		function downloadPdpDesign(kakaDesignId)
		{
			var zipUrl = '<?php echo $pdpUrl ?>rest/design-download?id='+kakaDesignId+'&zip=1' 
			 $.get(zipUrl, function(data, status){
				if(status == 'success')
				{
					var jsonData = data;
					var dataRes = jsonData.data;
					var fileZip = dataRes.file;
					var baseUrl = dataRes.baseUrl;
					window.location.href = baseUrl+ fileZip;
				}
				else
				{
					alert('Error ');
				}
			});
		}
	})
	</script>
<?php endif; ?>


