<?php $collection = $this->getCollection(); ?>
<?php $pdpConfig = Mage::getStoreConfig('integration'); ?>
<?php 
if(!isset($pdpConfig['setting']['enable']) || (isset($pdpConfig['setting']['enable']) && $pdpConfig['setting']['enable'] != 1))
{
	echo '<h1> Module Connect is disabled. </h1>';
	return false;
}
$pdpUrl = Mage::helper('integration')->getPdpLink();
$completedesignIds = $this->getAllCompleteDesigns();
?>
<?php $reDesignId = 0; ?>
<?php if($collection->getSize()): ?>
	<div class="customer-design">
		<?php if(Mage::getSingleton('core/session')->getPdpRedirect()) { $reDesignId  = Mage::getSingleton('core/session')->getPdpRedirect();  Mage::getSingleton('core/session')->setPdpRedirect(0); } ?>
		<div class="customer-design-header">
			<span class="customer-design-header-item customer-design-header-product"><?php echo $this->__('PRODUCT'); ?></span>
			<span class="customer-design-header-item customer-design-header-image"><?php echo $this->__('CUSTOMIZED DESIGN'); ?></span>
			<span class="customer-design-header-item customer-design-header-price"><?php echo $this->__('PRICE'); ?></span>
			<span class="customer-design-header-item customer-design-header-status"><?php echo $this->__('STATUS'); ?></span>
		</div>
		<div class="customer-design-content">
			<?php foreach($collection as $collect) : ?>
				<?php $designId = $collect->getDesignId(); ?>
				<div class="customer-design-content-item">
					<div class="customer-design-content-product">
						<?php $_product = $this->getMageProductById($collect->getMageProductId()); ?>
						<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(185); ?>" width="185" />
						<p class="product-name"><?php echo $_product->getName(); ?></p>
						<p class="product-sku"><?php echo $collect->getMageProductSku(); ?></p>
					</div>
					<div class="customer-design-content-image">
						<img alt="<?php echo $_product->getName(); ?>" src="<?php echo $pdpUrl.$collect->getThumbmail(); ?>" />
					</div>
					<div class="customer-design-content-price">
						<?php if(array_key_exists($designId,$completedesignIds)) : ?>
							<p><?php echo Mage::helper('core')->currency($completedesignIds[$designId],true,false); ?></p>
						<?php else : ?>
							<p><?php echo Mage::helper('core')->currency($collect->getPrice(),true,false); ?></p>
						<?php endif; ?>
					</div>
					<div class="customer-design-content-status">
						<?php $statusText = array('pedding'=> $this->__('Pendding'),'success'=>$this->__('Success')); ?>
						<?php $status = 'pedding'; 
							if(array_key_exists($designId,$completedesignIds))
							{
								$status = 'success';
							}
						?>
						<span class="design-status"><?php echo $statusText[$status]; ?></span>
						<span class="edit-design"><a href="<?php echo $pdpUrl.'?pid='.$collect->getPdpProductId() .'&tid='.$designId; ?>"><?php echo $this->__('Edit Design') ?></a></span>
						<?php if($status == 'success') : ?>
							<?php if($reDesignId == $designId) : ?>
								<span><?php echo $this->__('Design has created , Please click to Zip Design again'); ?></span>
							<?php endif; ?>
							<span class="zip-design"><span class="pdp-design-infor-item"><a class="pdp-design-infor-item-zip" id="pdp-design-infor-item-zip-<?php echo $designId; ?>" href="#"><?php echo $this->__('Zip Design') ?></a></span>
						<?php endif; ?>
					</div>
				</div>
				<input type="hidden" id="pdp-design-pdp-id-<?php echo $designId ?>" value="<?php echo $collect->getPdpProductId(); ?>" />
				<input type="hidden" id="pdp-design-current-url-<?php echo $designId ?>" value="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>" />
			<?php endforeach ?>
		</div>
	</div>
	<?php echo $this->getPagerHtml(); ?>
			<script type="text/javascript">
			jQuery(document).ready(function($){
				var checkPdpSessionUrl = '<?php echo $this->getUrl() ?>integration/customerdesign/setDpk';
				if($('.pdp-design-infor-item-zip').length)
				{
					$('.pdp-design-infor-item-zip').click(function(e){
						var elementId = $(this).attr('id');
						designId = elementId.replace('pdp-design-infor-item-zip-','');
						var pdpProductId = $('#pdp-design-pdp-id-'+designId).val();
						var zipUrl = '<?php echo $pdpUrl.'rest/design-download?'; ?>id='+designId+'&zip=1';
						var resturnUri = $('#pdp-design-current-url-'+designId).val();;
						var reload = '<?php echo $pdpUrl; ?>?pid='+pdpProductId+'&export-design='+designId+'&force-update-svg=1';
						reload += '&return-uri=' + encodeURIComponent(resturnUri);
						$.ajax({
							url: zipUrl,
							type: 'GET',
							success : function(res)
							{
								var jsonData = res;
								if(typeof jsonData === 'object')
								{
									
								}
								else
								{
									jsonData = JSON.parse(res);
								}
								var dataRes = jsonData.data;
								var fileZip = dataRes.file;
								var baseUrl = dataRes.baseUrl;
								window.location.href = baseUrl+ fileZip;
							},
							error : function(res)
							{
								var mResponseText = res.responseText;
								if(typeof mResponseText == 'object')
								{
									
								}
								else
								{
									mResponseText = JSON.parse(mResponseText);
								}
								if(mResponseText.errorCode && mResponseText.errorCode === 15)
								{
									checkPdpSession(checkPdpSessionUrl,designId,function(){
										if(confirm('<?php echo $this->__('We need create it again from Design Editor, Editor . Press OK then just wait , all done automatically !.'); ?>'))
										{
											window.location.href = reload;
										}
									})
								}else{
								 // alertModal('Error', $t(msg));
								}
							}
						})
						e.preventDefault();
					})
				}
				function checkPdpSession(url,designId,callback)
				{
					$.ajax({
							url: url,
							type: 'post',
							data : {design_id : designId},
							success : function(res)
							{
								callback();
							},
							error : function()
							{
								alert('Error');
							}
					})
				}
			})
		</script>
<?php else : ?>
<h1><?php echo $this->__('Item not found'); ?></h1>
<?php endif; ?>
